/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const computed: typeof import('vue')['computed']
  const onMounted: typeof import('vue')['onMounted']
  const ref: typeof import('vue')['ref']
  const watch: typeof import('vue')['watch']
}
